version: '3'

services:
    web:
        build: ./docker/web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            # wpのWP_INSTALL_PATHに合わせる
            - ./html:/var/www/html
            # - ./html:/var/www/html/ssl-2016
        depends_on:
            - wp
    wp:
        build: ./docker/wp
        volumes:
            - ./docker/wp/wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
            # wpのWP_INSTALL_PATHに合わせる
            - ./html:/var/www/html
            # - ./html:/var/www/html/ssl-2016
        depends_on:
            - db
    db:
        build: ./docker/db
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 43306:3306
    schemaspy:
        build: ./docker/schemaspy
        volumes:
            - ./erd/output:/output
        command: >
            -t mysql
            -dp /drivers_inc/mysql-connector-java-6.0.6.jar
            -host db
            -port 3306
            -db ${MYSQL_DATABASE}
            -s ${MYSQL_DATABASE}
            -u ${MYSQL_USER}
            -p ${MYSQL_PASSWORD}
            -connprops useSSL\\=false
            -debug
        links:
            - db
# volumes:
#     document_root:
#         driver_opts:
#             type: none
#             device: /usr/share/nginx/html
#             o: bind