version: '3.3'

services:
    web:
        build: ./docker/web
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - wp
    wp:
        build: ./docker/wp
        depends_on:
            - db
    db:
        build: ./docker/db
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 43306:3306
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
