version: '3'

services:
    web:
        build: ./docker/web
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/web/conf.d:/etc/nginx/conf.d
            # wpのWP_INSTALL_PATHに合わせる
            # - ./html:/var/www/html
            - ./html:/var/www/html/ssl-2016
        depends_on:
            - wp
    wp:
        build: ./docker/wp
        volumes:
            - ./docker/wp/php.ini:/usr/local/etc/php/php.ini
            # wpのWP_INSTALL_PATHに合わせる
            # - ./html:/var/www/html
            - ./html:/var/www/html/ssl-2016
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: password
            # WP_INSTALL_PATH: /var/www/html
            WP_INSTALL_PATH: /var/www/html/ssl-2016
            WP_BLOG_TITLE: テスト
            WP_ADMIN_USER: admin
            WP_ADMIN_PASSWORD: password
            WP_ADMIN_EMAIL: imo-tikuwa@example.com
            # WP_HTTP_ROOT: http://localhost
            WP_HTTP_ROOT: http://localhost/ssl-2016
        depends_on:
            - db
    db:
        build: ./docker/db
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - 43306:3306
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
# volumes:
#     document_root:
#         driver_opts:
#             type: none
#             device: /usr/share/nginx/html
#             o: bind